require("config.options")
require("config.keymaps")
require("core.lsp")

-- TODO: Figure out why I can't just require("plugins")
require("plugins.colorscheme")
require("plugins.lualine")
require("plugins.conform")
require("plugins.undotree")
require("plugins.treesitter")
require("plugins.indent-blankline")
require("plugins.mini-pick")
require("plugins.blink-cmp")
require("plugins.arrow")
